import type { CommandArgs } from "./types.js";

export function handleHelp(args: CommandArgs): number | undefined {
  const cmd = args.positionals[0] ?? "help";
  if (cmd !== "help" && cmd !== "--help" && cmd !== "-h") return;

  const { writeLine } = args.io;
  const out = args.io.out;
  writeLine(out, "git a5c <command> [--json] [--treeish <ref>] [--repo <path>] [--inbox-ref <ref>...]");
  writeLine(out, "  Read commands auto-pull from origin when safe (ff-only, clean tree).");
  writeLine(out, "  Write commands can use --sync with --commit to pull before and push after.");
  writeLine(out, "");
  writeLine(out, "Commands:");
  writeLine(out, "  status");
  writeLine(out, "  o [args...]");
  writeLine(out, "  issue list");
  writeLine(out, "  issue show <id>");
  writeLine(out, "  issue new --title <t> [--body <b>] [--stage-only|--commit]");
  writeLine(out, "  issue comment <id> -m <text> [--comment-id <id>] [--stage-only|--commit]");
  writeLine(out, "  issue edit-comment <commentId> --id <issueId> -m <text> [--stage-only|--commit]");
  writeLine(out, "  issue redact-comment <commentId> --id <issueId> [--reason <r>] [--stage-only|--commit]");
  writeLine(out, "  pr list");
  writeLine(out, "  pr show <prKey>");
  writeLine(out, "  pr propose --base <ref> --head <ref> --title <t> [--body <b>] [--stage-only|--commit]");
  writeLine(out, "  pr request --base <ref> --title <t> [--body <b>] [--stage-only|--commit]");
  writeLine(out, "  pr claim <prKey> --head-ref <ref> [-m <msg>] [--stage-only|--commit]");
  writeLine(out, "  pr bind-head <prKey> --head-ref <ref> [-m <msg>] [--stage-only|--commit]");
  writeLine(out, "  block <entityId> --by <issue|pr> [--op add|remove] [-m <note>] [--stage-only|--commit]");
  writeLine(out, "  gate needs-human <entityId> [--topic <t>] [-m <msg>] [--stage-only|--commit]");
  writeLine(out, "  gate clear <entityId> [-m <msg>] [--stage-only|--commit]");
  writeLine(out, "  agent heartbeat [--agent-id <id>] [--ttl-seconds N] [--entity <id>] [-m <status>] [--stage-only|--commit]");
  writeLine(out, "  agent run [--profile <name>] [--in <path|->] [--out <path>] [--stdout <path>] [--stderr <path>] [--model <m>] [--mcps <path>] [--config <path>]");
  writeLine(out, "  agent generate-context [--in <path>] [--template <uri>] [--var k=v]... [--out <path>] [--token <t>]");
  writeLine(out, "  ops deploy --entity <id> [--artifact <uri>] [-m <status>] [--stage-only|--commit]");
  writeLine(out, "  verify");
  writeLine(out, "  journal [--since <2h|2025-...>] [--limit N] [--types a,b] [--entity <id>] [--active]");
  writeLine(out, "  server [--port <port>] [--token <token>]");
  writeLine(out, "  ui [--port <port>]");
  writeLine(out, "  run dispatch --playbook <path>@<ver> [--run-id <id>] [--overrides-file <path>]");
  writeLine(out, "  run playbook --playbook <path>@<ver> [--run-id <id>] [--overrides-file <path>] [--max-iterations N] [--json]");
  writeLine(out, "  run reconcile [--run-id <id>] [--max-transitions N] [--dry-run] [--json]");
  writeLine(out, "  run tick [--run-id <id>] [--max-transitions N] [--dry-run] [--json]");
  writeLine(out, "  run sweep [--max N]");
  writeLine(out, "  run resume --run-id <id> [-m <msg>]");
  writeLine(out, "  run complete-step --run-id <id> [-m <msg>]");
  writeLine(out, "  hook exec --plan <path|-> [--dry-run]");
  writeLine(out, "  hooks install|uninstall");
  writeLine(out, "  webhook status");
  writeLine(out, "  webhook test --url <url> [--type <type>]");
  writeLine(out, "  parse --type codex [--pretty] [--out <path>]");
  return 0;
}
